// <auto-generated />
using Mando.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mando.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221005081350_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mando.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Snack",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut bibendum mauris. Donec vel nulla ut lacus pulvinar volutpat malesuada eu velit. Vestibulum nibh mauris, sagittis eu mattis sit amet, consequat et felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus eu mauris eu sapien maximus pretium at id leo. Nullam augue metus, ullamcorper ut sodales vitae, ultrices et dolor. Sed sagittis leo eu nibh rhoncus maximus. Donec enim odio, tristique vel turpis nec, vulputate scelerisque neque.",
                            ImageUrl = "https://dotnetmastery6502.blob.core.windows.net/mango/samosa.jpg",
                            Name = "Samosa",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Snack",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut bibendum mauris. Donec vel nulla ut lacus pulvinar volutpat malesuada eu velit. Vestibulum nibh mauris, sagittis eu mattis sit amet, consequat et felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus eu mauris eu sapien maximus pretium at id leo. Nullam augue metus, ullamcorper ut sodales vitae, ultrices et dolor. Sed sagittis leo eu nibh rhoncus maximus. Donec enim odio, tristique vel turpis nec, vulputate scelerisque neque.",
                            ImageUrl = "https://dotnetmastery6502.blob.core.windows.net/mango/kebab.jpg",
                            Name = "Kebab",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut bibendum mauris. Donec vel nulla ut lacus pulvinar volutpat malesuada eu velit. Vestibulum nibh mauris, sagittis eu mattis sit amet, consequat et felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus eu mauris eu sapien maximus pretium at id leo. Nullam augue metus, ullamcorper ut sodales vitae, ultrices et dolor. Sed sagittis leo eu nibh rhoncus maximus. Donec enim odio, tristique vel turpis nec, vulputate scelerisque neque.",
                            ImageUrl = "https://dotnetmastery6502.blob.core.windows.net/mango/swPie.jpg",
                            Name = "Sweet Pie",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut bibendum mauris. Donec vel nulla ut lacus pulvinar volutpat malesuada eu velit. Vestibulum nibh mauris, sagittis eu mattis sit amet, consequat et felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus eu mauris eu sapien maximus pretium at id leo. Nullam augue metus, ullamcorper ut sodales vitae, ultrices et dolor. Sed sagittis leo eu nibh rhoncus maximus. Donec enim odio, tristique vel turpis nec, vulputate scelerisque neque.",
                            ImageUrl = "https://dotnetmastery6502.blob.core.windows.net/mango/vegCurry.jpg",
                            Name = "Vegetable curry",
                            Price = 13.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
